---
title: "Bidirect_BIDS_data_overview"
author: "Niklas Wulms"
date: "7/17/2019"
output: html_document
---

# Library chunk

```{r}
library(tidyr)
library(stringr)
```


```{r}
rm(list=ls())
working_dir = "/media/niklas/spaceC/BIDS_Convert_test"
```

```{r setup}
require(knitr)
knitr::opts_knit$set(root.dir = working_dir)

```


```{r}
index_folder <- list.files(path = paste0(working_dir, "/nii"),
           full.names = TRUE,
           recursive=TRUE,
           include.dirs = TRUE) %>%
  str_replace(working_dir, "") 
```

# Nii information

```{r}

nii <- index_folder %>%
  str_subset("nii.gz") %>%
  str_replace("[:digit:]{5}-", "") %>%
  str_split("/", simplify = TRUE) %>%
  data.frame(stringsAsFactors = FALSE) %>%
  select(X3, X4, X5, X6) %>%
  rename(
    subject_id = X3,
    session = X4,
    sequence_type = X5,
    sequence = X6
  )


nii %>%
  group_by(session, sequence_type, sequence) %>%
  summarise(subjects = n_distinct(subject_id))

nii %>%
  group_by(session) %>%
  summarise(subjects = n_distinct(subject_id))



```



```{r}
json <- index_folder %>%
  str_subset(".json") %>%
  str_replace("/nii", "nii")

library(rjson)


# result <- fromJSON(file = json[1]) %>%
#   as.data.frame(stringsAsFactors = FALSE) %>%
#   mutate(Path = json[1])


# json_struct <- result_df[FALSE,]
# save(json_struct, file = "json_struct.RData")

load("json_struct.RData")

result_old = json_struct

for (i in 1:length(json)) {
  print(paste(i, json[i]))
  
  result_new <- fromJSON(file = json[i]) 
  
  result_new$ImageType <- paste(result_new$ImageType, collapse = ", ")
  result_new$ImageOrientationPatientDICOM <- paste(result_new$ImageOrientationPatientDICOM, collapse = ", ")
  result_new$Path <- json[i]
    
  result_new <- result_new %>%
    as.data.frame(stringsAsFactors = FALSE)
  
  result_old <- merge(result_new, result_old, all = TRUE)

}

save(result_old, file = "nii_metainformation.RData")


```


```{r}

```


