---
title: "Standardize sequence names"
author: "Niklas Wulms"
date: "7/31/2019"
output: html_document
---

```{r}
library(stringr)
library(dplyr)
library(tidyr)
```


```{r}

# On Linux
working_dir <- ("/media/niklas/My Book/Bidirect_Dicom/") 

# On Windows
# working_dir <- ("H:/Bidirect_Dicom/")
```

Working directory is set here

```{r setup}
require(knitr)
knitr::opts_knit$set(root.dir = working_dir)

```

# Load json csv

```{r}
json_meta <- read.table("json_files.csv",
                     header = TRUE,
              sep = ",",
              dec = ".",
              stringsAsFactors = FALSE
              #row.names = 0
              ) 
```



#### Extraction of sequence patterns

```{r}
# This is quality control of how your sequences are named (after removing of additional tags)
str_to_remove = "i000|36Jones20|TFElrsQFOV|fMRsshp|Patient_Aligned_|AWPLAN_|_-_WIP_|_TYPE_BRAIN_|MST_|_Blut|_-_|VWIP_|dcm2nii_"


sequences_used <- json_meta$ProtocolName %>% 
  str_replace_all(str_to_remove, "") %>%
  str_replace("a$", "_version1") %>%
  str_replace("b$", "_version2") %>%
  str_replace("c$", "_version3")

sequences_used_path <- json_meta$Path %>%
  str_replace(".json", "") %>%
  str_replace_all(str_to_remove, "") %>%
  str_replace("a$", "_version1") %>%
  str_replace("b$", "_version2") %>%
  str_replace("c$", "_version3") %>%
  str_split_fixed("/", n = 4)
  
# (seq_used_uniq <- unique(sequences_used_path[,4]) %>% sort())
  
# (seq_used_uniq <- unique(sequences_used) %>% sort())

```


```{r}
nii_temp_df <- json_meta$Path %>%
  str_replace(".json", ".nii") %>%
  str_split("/", n = 4, simplify = TRUE) %>%
  as.data.frame(stringsAsFactors = FALSE)

names(nii_temp_df)[1] <- "path"
names(nii_temp_df)[2] <- "session" 
names(nii_temp_df)[3] <- "subject"
names(nii_temp_df)[4] <- "sequence"

nii_temp_df$group <- str_sub(nii_temp_df$subject, 1, 1)
```

Here WIP (scanner preprocessed images) and Smartbrain images are filtered

```{r}
# Cleaning implausible sequence names
nii_temp_df$sequence <- str_replace_all(nii_temp_df$sequence, c("FLAIR_(2|ax).nii" = "FLAIR_TE120a.nii",
                                                                
                                                                "T2_TSE.nii" = "T2W_TSE.nii",
                                                                "T2_FFE_Blut_TR637" = "T2_FFE_Bluta",
                                                                "_Maske0" = "_a"
                                                                ))

# Bringing sequences into BIDS form
nii_temp_df$sequence_clean <- str_replace_all(nii_temp_df$sequence, c("3D|TFE|QFOV|lrs|36Jones20n|_-|Patient_Aligned_|AWPLAN_SMARTPLAN_TYPE_BRAIN_|i000|_1_0|1_0|fMRsshp" = "",
                                                                      "fMRssh2s35_" = "epi_emo_faces",
                                                                      
                                                                      "FLAIR_TE120" = "T2_flair",
                                                                      "T2_FFE_Blut" = "T2_star",
                                                                      "T2W_TSE" = "T2w",
                                                                      "mFFE_e" = "T2_star_e",

                                                                      "^mFFE_mod" = "T2_star_mod",
                                                                      "T2_TSE_2mm(?=(.nii|a.nii))" = "T2w_mod",
                                                                      
                                                                      
                                                                      
                                                                      "SURVEY|survey" = "Survey",
                                                                      "SmartBrain" = "Smartbrain")) %>%
  str_replace_all(c("(?<!tr)a.nii" = "_a.nii",
                    "b.nii" = "_b.nii",
                    "c.nii" = "_c.nii"))

nii_temp_df$bids_type <- str_replace_all(nii_temp_df$sequence_clean, c("T(1|1_a).nii" = "anat/T1w/",
                                                                       
                                                                       "T2_flai(r|r_a).nii" = "anat/T2_flair/",
                                                                       "T2_sta(r|r_a).nii" = "anat/T2_star/",
                                                                       "T2(w|w_a).nii" = "anat/T2w/",
                                                                       
                                                                       "^DT(I|I_a).nii" = "dwi/DTI/",
                                                                       
                                                                       "RS133.nii" = "func/rest/RS133",
                                                                       "RS7(2|2_a).nii" = "func/rest/RS72",
                                                                       "epi_emo_faces8(2|2_a).nii" = "func/EF/emotional_faces",
                                                                 
                                                                 # Here the plus sequences are filtered
                                                                "(T1mod|T1mod_a|T1mod_b).nii" = "anat/T1w_mod/",
                                                                 
                                                                "FLAIR_VIST(A|A_a).nii" = "anat/T2_flair_vista/",
                                                                 "T2_star_mod_e[:digit:]+.nii" = "anat/T2_star_mod/",
                                                                 "T2_star_mod_e[:digit:]+_ph.nii" = "anat/T2_star_mod_ph/",
                                                                 "T2w_mod" = "anat/T2w_mod/",
                                                                
                                                                # Here the implausible sequences are filtered
                                                                "Smartbrain" = "nii_implausible/Smartbrains_Smartbrain/",
                                                                "MPR" = "nii_implausible/Smartbrains_MPR/",
                                                                "Survey" = "nii_implausible/Smartbrains_Survey/",
                                                                
                                                                "T2_star_e" = "nii_implausible/test_T2_star_mod/",
                                                                
                                                                "^(?=d+(Reg|WIP_DTI|DTI))" = "nii_implausible/clin_dwi_d/",
                                                                "^(?=e+(Reg|WIP_DTI|DTI))" = "nii_implausible/clin_dwi_e/",
                                                                "^(?=fac+(Reg|WIP_DTI|DTI))" = "nii_implausible/clin_dwi_fac/",
                                                                "^(?=fa+(Reg|WIP_DTI|DTI))" = "nii_implausible/clin_dwi_fa/",
                                                                "iso(Reg|WIP|DTI|DWI)" = "nii_implausible/clin_dwi_iso/", 
                                                                "^Reg_DTI" = "nii_implausible/clin_dwi_reg/",
                                                                "^Reg_WIP" = "nii_implausible/clin_dwi_reg_WIP/",
                                                                
                                                                "T1mod_(cor|cor_a).nii" = "nii_implausible/clin_T1w_mod_cor/",
                                                                "T1mod_(tra|tra_a).nii" = "nii_implausible/clin_T1w_mod_tra/",
                                                                "VWIP_T1mod_SENSE" = "nii_implausible/clin_T1w_mod/",
                                                                
                                                                "FLAIR_VISTA_(tra|tra_a).nii" = "nii_implausible/clin_T2_flair_vista_tra/",
                                                                "FLAIR_VISTA_(cor|cor_a).nii" = "nii_implausible/clin_T2_flair_vista_cor/",
                                                                "VWIP_FLAIR_VISTA_SENSE" = "nii_implausible/clin_T2_flair_vista/",
                                                                
                                                                "VWIP_T1_cor.nii|T2_TSE_2mm_L_SENSE.nii|GM_only.nii|T1_TSE_2.5_mm_cor_L.nii|T1W_aTSE_cor_L.nii|T1W_VISTA.nii|T2W_SPIR_cor_L.nii|FFE_cor_0.7mmIV.nii|T2_TSE_SPIR_2.5mm_cor_L.nii" = "nii_implausible/Strange/"
)) %>%
  str_replace("VWIP_", "") %>%
  str_extract("^[:graph:]*/[:graph:]*/")


nii_temp_df$type = str_extract(nii_temp_df$bids_type, "^[:alpha:]*/")

nii_temp_df <- nii_temp_df %>%
  mutate(session_BIDS = str_replace_all(session, c("Baseline" = "1",  
                                                                 "FollowUp2" = "3", 
                                                                 "FollowUp3" = "4",  
                                                                 "FollowUp2_plus" = "3_plus",  
                                                                 "FollowUp3_plus" = "4_plus", 
                                                                 "FollowUp" = "2")),
         group_session_plus = paste("Gr", group, "Ses", session_BIDS, sep = "_"),
         group_session = str_replace(group_session_plus, "_plus", ""),
         sequence_clean1 = str_replace_all(sequence_clean, "(VW|W)IP_|_SENSE|_ax_sag|_SCG|_HG|_NV16|_TR637", ""))
         
nii_temp_df$plus = ifelse(str_detect(nii_temp_df$bids_type, "T1w_tra|T(1|2)w_mod|T2_(flair_vista|star_mo(d|d_ph))") == 0,
                          "base_protocol", "plus_protocol")

# nii_temp_df$sequence_BIDS = str_replace(nii_temp_df$sequence_clean)

nii_temp_df$seq_clean = ifelse(str_detect(nii_temp_df$bids_type, "nii_implausible") == 1,
                            paste("", nii_temp_df$bids_type, nii_temp_df$session, "/", nii_temp_df$subject, "/", nii_temp_df$sequence_clean, ".gz", sep = ""),
                            paste("BIDS/", nii_temp_df$plus, "/sub-", nii_temp_df$subject, "/ses-", nii_temp_df$session_BIDS, "/", nii_temp_df$type, "sub-", 
                                  nii_temp_df$subject, "_ses-", nii_temp_df$session_BIDS, "_", nii_temp_df$sequence_clean, ".gz", sep = ""))


head(nii_temp_df$seq_clean)

nii_temp_df %>%
  select(plus, sequence_clean, bids_type, sequence) %>%
  group_by_all() %>%
  count() %>%
  arrange(plus, bids_type)
  
```




# Binding old and new dataframe together

```{r}
json_meta_all <- cbind(nii_temp_df, json_meta) %>%
  rename(
    old_json = Path,
    new_nii = seq_clean,
  ) %>%
  mutate(old_nii = str_replace(old_json, "json$", "nii.gz"),
         new_json = str_replace(new_nii, "nii.gz$", "json")) %>%
    select(old_nii, new_nii, everything())


json_meta_all <- json_meta_all %>%
  mutate(ImageType = str_replace(ImageType, "ORIGINAL, PRIMARY, ", "")) %>%

  rename(
    SliceGap = SpacingBetweenSlices,
    AcqMatrix = AcquisitionMatrixPE,
    ReconMatrix = ReconMatrixPE,
    PhaseDirection = InPlanePhaseEncodingDirectionDICOM,
    EchoTrain = EchoTrainLength,
    MRType = MRAcquisitionType,
    Averages = NumberOfAverages,
    PhaseAxis = PhaseEncodingAxis,
    Raw = RawImage,
    ScanSeq = ScanningSequence,
    Options = ScanOptions,
    Variant = SequenceVariant
  ) 
```

```{r}
# Duplicate paths
json_meta_all %>%
  select(new_nii) %>%
  group_by_all() %>%
  count() %>%
  filter(n > 1 ) %>%
  filter(n < 7) %>%
  left_join(json_meta_all)

# Sequences with (_a, _b, _c) and their original files
nii_duplicates <- json_meta_all %>%
  select(new_nii, subject, session, bids_type) %>%
  filter(str_detect(new_nii, "Smartbrain|clin") == 0) %>%
  filter(str_detect(new_nii, pattern = "_(a|b|c).nii") == 1) %>%
  select(-new_nii) %>%
  left_join(json_meta_all) %>%
  select(new_nii, everything()) %>%
  mutate(duplicate = "duplicate")

nii_duplicates


```

```{r}
json_meta_all %>%
  select(bids_type, contains("nii"), contains("json"))
```

```{r}
save(nii_duplicates, file = "duplicates.Rdata")
save(json_meta_all, file = "json_all.Rdata")
```









