---
title: "JSON_cleanup"
author: "Niklas Wulms"
date: "7/31/2019"
output: html_document
---

```{r}
library(stringr)
library(dplyr)
library(tidyr)
```


```{r}

# On Linux
working_dir <- ("/media/niklas/My Book/Bidirect_Dicom/") 

# On Windows
# working_dir <- ("H:/Bidirect_Dicom/")
```

Working directory is set here

```{r setup}
require(knitr)
knitr::opts_knit$set(root.dir = working_dir)

```

# Load json csv

```{r}
json_meta <- read.table("json_files.csv",
                     header = TRUE,
              sep = ",",
              dec = ".",
              stringsAsFactors = FALSE
              #row.names = 0
              ) 
```



#### Extraction of sequence patterns

```{r}
# This is quality control of how your sequences are named (after removing of additional tags)
str_to_remove = "i000|36Jones20|TFElrsQFOV|fMRsshp|Patient_Aligned_|AWPLAN_|_-_WIP_|_TYPE_BRAIN_|MST_|_Blut|_-_|VWIP_|dcm2nii_"


sequences_used <- json_meta$ProtocolName %>% 
  str_replace_all(str_to_remove, "") %>%
  str_replace("a$", "_version1") %>%
  str_replace("b$", "_version2") %>%
  str_replace("c$", "_version3")

sequences_used_path <- json_meta$Path %>%
  str_replace(".json", "") %>%
  str_replace_all(str_to_remove, "") %>%
  str_replace("a$", "_version1") %>%
  str_replace("b$", "_version2") %>%
  str_replace("c$", "_version3") %>%
  str_split_fixed("/", n = 4)
  
(seq_used_uniq <- unique(sequences_used_path[,4]) %>% sort())
  
(seq_used_uniq <- unique(sequences_used) %>% sort())

```


```{r}
nii_temp_df <- json_meta$Path %>%
  str_replace(".json", ".nii") %>%
  str_split("/", n = 4, simplify = TRUE) %>%
  as.data.frame(stringsAsFactors = FALSE)

names(nii_temp_df)[1] <- "path"
names(nii_temp_df)[2] <- "session" 
names(nii_temp_df)[3] <- "subject"
names(nii_temp_df)[4] <- "sequence"

nii_temp_df$group <- str_sub(nii_temp_df$subject, 1, 1)
```

Here WIP (scanner preprocessed images) and Smartbrain images are filtered

```{r}
nii_temp_df$WIP <- ifelse(str_detect(nii_temp_df$sequence, "WIP|(e|d|fa|fac|iso|iso_)(Reg|DTI)|^Reg") == 1, "WIP", "")
nii_temp_df$smartbrain <- ifelse(str_detect(nii_temp_df$sequence, "SMARTPLAN|MPR|SmartBrain|MST|survey|SURVEY") == 1, "Smartbrain", "")
```


Check here, if the WIP and Smartbrain assignment fits - we split the data here

```{r}
nii_temp_df %>%
  select(sequence, WIP, smartbrain) %>%
  mutate(sequence_clean = str_replace_all(sequence, "TFE|lrs|36Jones20n|fMRssh|_-|Patient_Aligned_|AWPLAN_SMARTPLAN_TYPE_BRAIN_|i000|VWIP_|WIP_|_SENSE|_1_0|1_0", "")) %>%
  group_by_all() %>%
  count() %>%
  arrange(WIP, smartbrain, sequence_clean)
```



```{r}

split_df <- split(nii_temp_df, nii_temp_df$smartbrain)

nii_clean_df <- split_df[[1]]

smartbrain_df2 <- nii_temp_df[nii_temp_df$smartbrain == "Smartbrain",]
wip_df <- nii_temp_df[nii_temp_df$smartbrain == "Smartbrain",]

  split_df <- split(nii_clean_df, nii_clean_df$WIP)

nii_clean_df <- split_df[[1]]
wip_df <- split_df[[2]]
```


```{r}
remove_smartbrain_ids <- "Patient_Aligned_|i000|_HG|_NV16_HN|VWIP_|AWPLAN_SMARTPLAN_TYPE_BRAIN_|SCG_|ax_sag_|AX|_MST|HG_"
remove_wip_ids <- "36Jones20n|VWIP_|WIP_|_-|TFE" 
remove_
```


```{r}
nii_clean_df %>%
  select(sequence, WIP, smartbrain) %>%
  unique() %>%
  arrange(WIP, sequence)

smartbrain_df %>%
  select(sequence, WIP, smartbrain) %>%
  mutate(sequence_clean = str_replace_all(sequence, remove_smartbrain_ids, ""),
         sequence_clean = str_replace_all(sequence_clean, regex("survey", ignore_case = TRUE), "Survey"),
         sequence_clean = str_replace_all(sequence_clean, regex("smartbrain", ignore_case = TRUE), "Smartbrain")) %>%
  unique() %>%
  arrange(sequence_clean)

wip_df %>%
  select(sequence, WIP, smartbrain) %>%
  mutate(sequence_clean = str_replace_all(sequence, remove_wip_ids, "")) %>%
  group_by_all() %>%
  count() %>%
  arrange(sequence_clean)


```


```{r}
str_to_remove = "i000|Jones20|36|TFE|lrs|_TE120|QFOV|SMARTPLAN_TYPE_BRAIN_|SENSE|1_0|fMRssh|Patient_Aligned_|AWPLAN_|_-_WIP_|_TYPE_BRAIN_|MST_|_Blut|_-_|VWIP_|dcm2nii_|_-_|_$|SURVEY_|survey_|isoDWI_|SPIR_"




nii_temp_df$sequence_halfclean <- nii_temp_df$sequence %>%
  str_replace(".nii", "") %>%
  
  # remove strange patterns
  str_replace("Reg_-_WIP_DTI36Jones20n", "Reg_-_DTI36Jones20n_WIP") %>%
  str_replace("WIP_DTI36Jones20n", "DTI36Jones20n_WIP") %>%
  str_replace("VWIP_3DT1TFEmod_SENSE", "3DT1TFEmod_SENSE_WIP") %>%
  str_replace("VWIP_FLAIR_VISTA_SENSE", "FLAIR_VISTA_SENSE_WIP") %>%
  
  str_replace("(?<=[:graph:]{1,3})Reg", "") %>%
  str_replace("^_i(?=[:digit:]{5}$)", "MPR_i") %>%
  str_replace_all(str_to_remove, "") %>%
  str_replace("tra", "trans") %>%
  str_replace("a$", "_version1") %>%
  str_replace("b$", "_version2") %>%
  str_replace("c$", "_version3") %>%

  # change strange sequence names

  str_replace("TSE_2mm_L", "TSE_2mm") %>%
  str_replace("2s35_82", "RS35") %>%
  str_replace("pRS", "RS") %>%
  
  # Duplicate sequence names
  str_replace("VWIP_", "WIP_") %>%
  str_replace("(?<=[:graph:]WIP[:graph:]).nii", "_WIP") %>%
  str_replace("WIP_", "") %>%

  str_replace("_Eq_1", "_version1") %>%
  str_replace("_ADC", "_version1") %>%
  str_replace("_TR637", "_version1") %>%

  str_replace_all("__", "_") %>%
  str_replace("__", "_") %>%
  str_replace("^_|_$", "") %>%
  str_replace("DTIn", "DTI")
```


```{r}
```


```{r}
nii_temp_df %>% 
  group_by(sequence) %>%
  select(sequence_halfclean, sequence, WIP, smartbrain) %>%
  unique() %>%
  arrange(sequence)

nii_temp_df %>% 
  group_by(sequence, sequence_halfclean) %>%
  count() %>%
  arrange(sequence)
```


```{r}
```


```{r}
nii_temp_df$sequence_clean <- nii_temp_df$sequence_halfclean %>%
  # assign imaging groups
  str_replace("RS72", "/func/rest_short/") %>%
  str_replace("RS133", "/func/rest_long/") %>%
  str_replace("RS35", "/func/emotional_faces/") %>%
  str_replace("^(?=[:graph:]*T1(?!mod))", "/anat/T1w/") %>%
  str_replace("^(?=[:graph:]*(T2_TSE(?!_2mm)|T2W))", "/anat/T2w/") %>%
  str_replace("^(?=[:graph:]*(T2_FFE))", "/anat/T2_star/") %>%
  str_replace("FLAIR(?!_VISTA)", "/anat/T2_FLAIR/") %>%

    str_replace("^(?=[:graph:]*(invalidName))", "/other/unknown/") %>%

  # Smartbrains / Survey
  str_replace("^(?=[:graph:]*(SmartBrain))", "/other/Smartbrain/") %>%
  str_replace("^(?=[:graph:]*(MPR))", "/other/Smartbrain/") %>%
  str_replace("^(?=[:graph:]*(MST|NV16|AX|ax_sag|HG_|SCG_))", "/other/Smartbrain/") %>%
  str_replace("^(?=[:digit:]{2})", "/other/Smartbrain/") %>%
  
  # DTI sequences
  str_replace("^(?=[:graph:]*DTI)", "/dwi/DTI/") %>%
  str_replace("DTIn", "DTI") %>%
  str_replace("iso_DTI", "isoDTI") %>%
  str_replace("/dwi/DTI/DTI$", 	"/dwi/DTI_base/DTI") %>%
  str_replace("DTI/dDTI", "DTI_dReg/dDTI") %>%
  str_replace("DTI/faDTI", "DTI_faReg/faDTI") %>%
  str_replace("DTI/facDTI", "DTI_facReg/facDTI") %>%
  str_replace("DTI/isoDTI", "DTI_isoReg/isoDTI") %>%
  str_replace("DTI/RegDTI", "DTI_Reg/RegDTI") %>%
  str_replace("DTI/eDTI", "DTI_eReg/eRegDTI") %>%
  str_replace("DTI_isoReg/isoDTI_Maske0", "DTI_isoReg_Maske0/isoDTI_Maske0") %>%

  
  # PLUS sequences
  str_replace("^(?=[:graph:]*(FLAIR_VISTA))", "/anat/T2_FLAIR_VISTA/") %>%
  str_replace("^(?=[:graph:]*(T2_TSE_2mm))", "/anat/T2w_2mm/") %>%
  str_replace("^(?=[:graph:]*(3DT1mod))", "/anat/T1w_mod/") %>%
  str_replace("^(?=[:graph:]*(mFFE_mod_e[:digit:]_ph$))", "/anat/T2star_plus_mod_ph/") %>%
  str_replace("^(?=[:graph:]*(mFFE_mod_e[:digit:]$))", "/anat/T2star_plus_mod/") %>%
  str_replace("^(?=[:graph:]*(mFFE_e[:digit:]_ph$))", "/anat/T2star_plus_ph/") %>%
  str_replace("^(?=[:graph:]*(mFFE_e[:digit:]$))", "/anat/T2star_plus/") %>%
  
  # split and only append first part of the new name
  str_extract("^/[:graph:]*/[:graph:]*/")




nii_temp_df %>%
  group_by(sequence_clean, sequence_halfclean, sequence) %>%
  count()
```



```{r}
# Version (same sequence multiple times in one dicom of a subject)
nii_temp_df$version <- ifelse(str_detect(nii_temp_df$sequence_halfclean, "version") == 1, "alternative", "first_seq")



# Image classes variable
nii_temp_df$image_classes <- nii_temp_df$sequence_clean %>%
  str_extract("/[:graph:]*(?=/[:graph:]*/)") 

# Extract "plus" information
nii_temp_df$plus <- ifelse(str_detect(nii_temp_df$session, regex("plus", ignore_case = TRUE)), "plus", "base")

# Set "plausible" sequences

nii_temp_df$plausible <- ifelse(nii_temp_df$sequence_halfclean %in% c("3DT1", 
                                                                      "FLAIR", "T2_FFE", "T2W_TSE", 
                                                                      
                                                                      "DTI",
                                                                      
                                                                      "RS72", "RS133", "RS35",
                                                                      
                                                                      # Plus sequences
                                                                      "3DT1mod", "3DT1mod_cor", "3DT1mod_trans", 
                                                                      "T2_TSE_2mm", "FLAIR_VISTA", "mFFE_mod",
                                                                     paste("T2star_plus_mod_e", 1:8, sep = ""), 
                                                                     paste("T2star_plus_mod_e", 1:8, sep = "", "_ph"),
                                                                     paste("T2star_plus_e", 1:8, sep = ""), 
                                                                     paste("T2star_plus_e", 1:8, sep = "", "_ph")), 
                                "plausible", "not plausible")

nii_temp_df %>%
  group_by(plausible, sequence_clean, sequence_halfclean, sequence) %>%
  count() %>%
  arrange(plausible, desc(n))
```


```{r}
nii_temp_df$image_classes_prio <- nii_temp_df$sequence_clean %>%
  str_replace("/anat/T1w/|/anat/T2w/|/anat/T2_FLAIR/|/anat/T2_star/|/dwi/DTI_base/|/dwi/DTI/|
              /func/rest_(short|long)/|/func/emotional_faces/", "1_base_sequences") %>%
  
  str_replace("/anat/T1w_mod/|/anat/T2_FLAIR_VISTA/|/anat/T2w_2mm/|/anat/T2star_plus_mod/|
              /anat/T2star_plus_ph/|/anat/T2star_plus_mod_ph/", "2_plus_sequences") %>%
  
  str_replace("/other/unknown/|/dwi/DTI_[:alpha:]*Reg/|/dwi/DTI_isoReg_Maske0/|/anat/T2star_plus/", "3_low_priority") %>%
  
  str_replace("/other/Smartbrain/|/other/MST/|/other/mprage/", "4_delete")
```


# Binding old and new dataframe together

```{r}
json_meta_all <- cbind(json_meta, nii_temp_df)

json_meta_all <- json_meta_all %>%
  mutate(ImageType = str_replace(ImageType, "ORIGINAL, PRIMARY, ", "")) %>%
  rename(
    SliceGap = SpacingBetweenSlices,
    AcqMatrix = AcquisitionMatrixPE,
    ReconMatrix = ReconMatrixPE,
    PhaseDirection = InPlanePhaseEncodingDirectionDICOM,
    EchoTrain = EchoTrainLength,
    MRType = MRAcquisitionType,
    Averages = NumberOfAverages,
    PhaseAxis = PhaseEncodingAxis,
    Raw = RawImage,
    ScanSeq = ScanningSequence,
    Options = ScanOptions,
    Variant = SequenceVariant
  ) %>%
  mutate(session_BIDS = str_replace_all(json_meta_all$session, c("Baseline" = "1",  
                                                                 "FollowUp2" = "3", 
                                                                 "FollowUp3" = "4",  
                                                                 "FollowUp2_plus" = "3_plus",  
                                                                 "FollowUp3_plus" = "4_plus", 
                                                                 "FollowUp" = "2")),
         sequence_only = str_replace(json_meta_all$sequence_clean, "^/[:alpha:]+/", ""),
         sequence_only = str_replace(sequence_only, "/", ""),
         seq_clean = paste("/nii/sub-", subject, "/ses-", session_BIDS, image_classes, "/sub-", subject, "_ses-", session_BIDS, "_", sequence_only, ".nii", sep = ""),
         seq_clean_avg = paste("/nii/sub-", subject, "/ses-", session_BIDS, image_classes, "/sub-", subject, "_ses-", session_BIDS, "_", sequence_only, "_avg_", Averages, ".nii",  sep = ""))
```


```{r}

json_meta_all$sequence_halfclean <- json_meta_all$sequence_halfclean %>%
  str_replace_all("\\.", "_")

json_meta_all$excl_reason <- str_replace_all(json_meta_all$sequence_halfclean, c("SmartBrain|SmartBrain_(01|02)|MPR_(01|23|39)|01|04|07|HG_(05|08|09|11)|SCG_(08|14)|MPR|MPR_40|MST|AX" = "excl_Smartbrain",
                                                                          
                                                                          "(Reg|d|fa|fac|iso|iso_|e)DTI" = "excl_clindti",
                                                                          
                                                                          "(3DT1|3DT1mod)_(cor|trans|WIP)" = "excl_clint1",
                                                                          
                                                                          "FLAIR_VISTA_(cor|trans|WIP)" = "excl_clinvista",
                                                                          
                                                                          "mFFE_e[:digit:]" = "excl_testmessungen",
                                                                          
                                                                          "FFE3D|GM_only|T1W_aTSE|T1W_VISTA|T1_TSE_2_5_mm|T2_TSE_2_5mm_cor_L|T2W_cor_L" = "excl_strange",
                                                                          
                                                                          "version[:digit:]?$" = "excl_double"))

json_meta_all$excl_reason_clean = ifelse(str_detect(json_meta_all$excl_reason, "excl") == 1, json_meta_all$excl_reason, "keep")
         


json_meta_all$excl_reason2 =  json_meta_all$excl_reason_clean %>%
  str_replace("^[:graph:]+(?=excl_)", "") 

json_meta_all$excl_reason2 =  json_meta_all$excl_reason_clean %>%
  str_extract_all("excl_[:alnum:]+", simplify = TRUE)

json_meta_all$excl_reason2 = paste(json_meta_all$excl_reason2[,1], json_meta_all$excl_reason2[,2])


json_meta_all$exclude = ifelse(json_meta_all$excl_reason_clean == "keep", "keep", "exclude")
```


```{r}
```


```{r}
json_meta_all %>% 
  group_by(exclude, excl_reason, excl_reason2, sequence_halfclean, excl_reason, excl_reason2) %>% 
  count() %>% 
  arrange(exclude, excl_reason2)

save(json_meta_all, file = "json_all.Rdata")
```


```{r}
```


```{r}
json_meta_all %>% 
  filter(exclude == "keep")
```








