---
title: "BD_BIDS_Converter"
author: "Niklas Wulms"
date: "7/4/2019"
output: html_document
---

Input: Folder with dicoms, "empty_df.Rdata"
Output: "json_files.csv"

```{r}
library(tidyr)
library(stringr)
library(dplyr)
library(rjson)
```


```{r}
rm(list=ls())
working_dir = ("/media/niklas/My Book/Bidirect_Dicom/") 
```


```{r setup}
require(knitr)
knitr::opts_knit$set(root.dir = working_dir)

```

# Indexing of the folder for jsons

```{r}

search_folder <- "/nii_temp"

library(tictoc)
tic()
json <- list.files(path = paste0(working_dir, search_folder),
                           pattern = ".json",
           full.names = TRUE,
           recursive=TRUE,
           include.dirs = TRUE) %>%
  str_replace(working_dir, "") %>%
  str_replace("/nii_temp", "nii_temp")
toc()
```


```{r}
rm(json_proc)

#result_old= result

if (file.exists("json_files.csv") == 1) {
  json_proc <- read.table("json_files.csv",
                     header = TRUE,
              sep = ",",
              dec = ".",
              stringsAsFactors = FALSE
              #row.names = 0
              ) 
  
  json_processed <- json_proc$Path
  
  # checks for already processed jsons
  json <- setdiff(json, json_processed)
}
```

```{r}

load("/media/niklas/My Book/Bidirect_Dicom/empty_result_df.Rdata")

for (i in 1:length(json)) {
  if (i %% 1000 == 0) {
    toc()
    print(paste(i, "of length", length(json), round(i/length(json)*100, 2), "%", "json:", json[i]))
    tic()
  }
 
  
  result_new <- fromJSON(file = json[i]) 
  
  result_new$ImageType <- paste(result_new$ImageType, collapse = ", ")
  result_new$ImageOrientationPatientDICOM <- paste(result_new$ImageOrientationPatientDICOM, collapse = ", ") 
  
  
  result_new <- result_new %>%
    as.data.frame(stringsAsFactors = FALSE) %>%
    select(-Modality, -MagneticFieldStrength, -SeriesDescription, -Manufacturer : -ProcedureStepDescription, -AcquisitionNumber, -CoilString, -ConversionSoftware, -ConversionSoftwareVersion) %>%
    mutate(Path = json[i]) %>%
    unique()
  

    result_new <-merge(result_df_empty, result_new, all = TRUE, sort = F) 
    result_new <- result_new[sort(names(result_df_empty))]
    
    
    result_new_1 <- result_new[, order(colnames(result_df_empty),decreasing=TRUE)]
  #  glimpse(result_new)

  if (file.exists("json_files.csv") == 0) {
    write.table(result_new,
                "json_files.csv",
                sep = ",",
                dec = ".",
                qmethod = "double",
                row.names = FALSE)
    
   # result_test = result_new
    # result = result_new[0,]
  } else {
# Here data gets only appended to csv
    write.table(result_new,
                "json_files.csv",
                sep = ",",
                dec = ".",
                qmethod = "double",
                row.names = FALSE,
                append = TRUE,
                col.names = FALSE)
   # result_test <- merge(result_test, result_new, all = TRUE, sort = F)
    # result <- result[0,]
  }
  # 
  
}

toc()
```



