---
title: "bd_mrt_metadaten_sas_export"
author: "Niklas Wulms"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: lumen
    highlight : tango
    code_folding: hide
    df_print: paged
    toc: true
    number_sections: true
    toc_float: false
    collapsed: false
    toc_depth: 5
---

<style type="text/css">
.main-container {
  max-width: 2800px;
  margin-left: auto;
  margin-right: auto;
}
</style>
---

```{r}
library(stringr)
library(dplyr)
library(tidyr)
```


```{r}

# On Linux
working_dir <- ("/home/niklas/Documents/") 

# On Windows
# working_dir <- ("H:/Bidirect_Dicom/")
```

Working directory is set here

```{r setup}
require(knitr)
knitr::opts_knit$set(root.dir = working_dir)

```

```{r}
load("json_all_deanonymized.Rdata")
```



```{r}
json_meta_all2 <- json_meta_all %>%
    filter(str_detect(new_nii, "implausible") == 0) %>%
  filter(str_detect(new_nii, pattern = "_(a|b|c).nii") == 0) %>%
  filter(str_detect(new_nii, "e(2|3|4|5|6|7)|e1_ph") == 0) %>%
  select(subject, PatientID, PatientSex, PatientBirthDate, PatientWeight, session, sequence_clean1, type, AcquisitionDateTime) %>%
  mutate(sequence_clean1 = str_replace(sequence_clean1, ".nii", ""),
         sequence_clean1 = str_replace(sequence_clean1, "FLAIR_VISTA", "T2_flair_vista"),
         sequence_clean1 = str_replace(sequence_clean1, "T1mod", "T1_mod"),
         AcquisitionDate = str_extract(AcquisitionDateTime, "^[:graph:]+T") %>% str_replace("T", ""),
#         session = str_replace(session, "_plus", ""),
         session = str_replace(session, "Baseline", "s0"),
         session = str_replace(session, "FollowUp$", "s2"),
         session = str_replace(session, "FollowUp2", "s4"),
         session = str_replace(session, "FollowUp3", "s6"),
         sequence_clean = str_to_lower(sequence_clean1),
        sequence_clean = str_replace(sequence_clean, "t2w_mod", "t2w_mod"),
        sequence_clean = str_replace(sequence_clean, "t1_mod", "t1_mod"),
        sequence_clean = str_replace(sequence_clean, "t2_flair_vista", "t2_flair_mod"),
        sequence = paste0("mrt_", type, sequence_clean),
        sequence = str_replace(sequence, "/", "_"),
        idbidirect = subject)

patient_info <- json_meta_all2 %>%
  select(idbidirect, session, AcquisitionDate, PatientSex, PatientBirthDate, PatientWeight) %>%
  unique()

# patient_weight <- json_meta_all2 %>%
#   select(subject, session3, PatientWeight) %>%
#   unique() %>%
# #  group_by_all() %>% count () %>% filter(n > 1)
#   spread(session3, PatientWeight)
```



```{r}
# strange non unique subjects
switch_gender <- json_meta_all2 %>%
  select(idbidirect, PatientSex) %>% 
  unique() %>%
  select(idbidirect) %>%
  group_by(idbidirect) %>%
  count() %>%
  filter(n > 1) %>%
  left_join(patient_info) %>%
  select(idbidirect, session, PatientSex) 

switch_birthdate <- json_meta_all2 %>%
  select(idbidirect, PatientBirthDate) %>% 
  unique() %>%
  select(idbidirect) %>%
  group_by(idbidirect) %>%
  count() %>%
  filter(n > 1) %>%
  left_join(patient_info) %>%
  select(idbidirect, session, PatientBirthDate) 

switch_weight <- json_meta_all2 %>%
  select(idbidirect, session, PatientWeight) %>%
  unique() %>%
  select(idbidirect, session) %>%
  group_by_all() %>% count() %>% filter(n > 1) %>%
  left_join(patient_info) %>%
  select(idbidirect, session, PatientWeight)
```

# Strange metadata {.tabset}

## switch gender

```{r}
library(DT)

switch_gender %>%   datatable(filter = 'top', 
            extensions = list('Buttons' = NULL,
                              'Scroller' = NULL,
                              'ColReorder' = NULL),
            
            options = list(
                           dom = 'Bfrtip', 
                           buttons = list(c('copy', 'csv', 'excel', 'pdf', 'print'), 
                                          I('colvis')),
                           deferRender = TRUE,
                           scrollX = 600,
                           scrollY = 700, 
                           scroller = TRUE,
                           ColReorder = TRUE,
                           pageLength = 20
                           )
    )
```

## switch birthdate

```{r}
switch_birthdate %>%   datatable(filter = 'top', 
            extensions = list('Buttons' = NULL,
                              'Scroller' = NULL,
                              'ColReorder' = NULL),
            
            options = list(
                           dom = 'Bfrtip', 
                           buttons = list(c('copy', 'csv', 'excel', 'pdf', 'print'), 
                                          I('colvis')),
                           deferRender = TRUE,
                           scrollX = 600,
                           scrollY = 700, 
                           scroller = TRUE,
                           ColReorder = TRUE,
                           pageLength = 20
                           )
    )
```

## switch weight

```{r}
switch_weight %>%   datatable(filter = 'top', 
            extensions = list('Buttons' = NULL,
                              'Scroller' = NULL,
                              'ColReorder' = NULL),
            
            options = list(
                           dom = 'Bfrtip', 
                           buttons = list(c('copy', 'csv', 'excel', 'pdf', 'print'), 
                                          I('colvis')),
                           deferRender = TRUE,
                           scrollX = 600,
                           scrollY = 700, 
                           scroller = TRUE,
                           ColReorder = TRUE,
                           pageLength = 20
                           )
    )
```

#


```{r}

bidirect_neuroimaging_overview <- json_meta_all2 %>%
  group_by(idbidirect, session, sequence) %>%
  count() %>%
  left_join(patient_info) %>%
  arrange(session) %>%
  rename(mrt_exam_date = AcquisitionDate,
         survey = session,
         mrt_sequence = sequence,
         mrt_n = n,
         mrt_patient_sex = PatientSex,
         mrt_patient_birthdate = PatientBirthDate,
         mrt_patient_weight = PatientWeight)

s0 <- bidirect_neuroimaging_overview %>%
  filter(survey == "s0")

s2 <- bidirect_neuroimaging_overview %>%
  filter(survey == "s2")

s4 <- bidirect_neuroimaging_overview %>%
  filter(str_detect(survey, "s4|s4_plus") == 1)

s6 <- bidirect_neuroimaging_overview %>%
  filter(str_detect(survey, "s6|s6_plus") == 1)


# This is the overview!




```


```{r}
# library(haven)
# write_sas(bidirect_neuroimaging_overview, "bidirect_neuroimaging_haven.sasb7dat")

# setwd("/mnt/itz030/Projekte_laufend/BiDirect/Dokumentation/MRT/Niklas")

getwd()
library(foreign)
write.foreign(s0, 
              "s0_mrt.txt", 
              "s0_mrt.sas", 
              package="SAS")

write.foreign(s2, 
              "s2_mrt.txt", 
              "s2_mrt.sas", 
              package="SAS")

write.foreign(s4, 
              "s4_mrt.txt", 
              "s4_mrt.sas", 
              package="SAS")

write.foreign(s6, 
              "s6_mrt.txt", 
              "s6_mrt.sas", 
              package="SAS")



# write_xpt(bidirect_neuroimaging_overview, "bidirect_neuroimaging_haven.xpt", version = 8)
# 
# library(SASxport)
# write.xport(bidirect_neuroimaging_overview, file= "bidirect_neuroimaging_SASxport.xpt")
```
